skeleton-alpinelinux: use host-alpine-keys
This uses the alpine's keys to build the rootfs and drops the apk's
option --allow-untrusted.

Fixes:

	buildroot:~# apk add calamares
	fetch http://nl.alpinelinux.org/alpine/latest-stable/main/aarch64/APKINDEX.tar.gz
	ERROR: http://nl.alpinelinux.org/alpine/latest-stable/main: UNTRUSTED signature
	WARNING: Ignoring APKINDEX.3f8e9ca0.tar.gz: No such file or directory
	fetch http://nl.alpinelinux.org/alpine/latest-stable/community/aarch64/APKINDEX.tar.gz
	ERROR: http://nl.alpinelinux.org/alpine/latest-stable/community: UNTRUSTED signature
	WARNING: Ignoring APKINDEX.0a5ec95f.tar.gz: No such file or directory
	ERROR: unsatisfiable constraints:
	  calamares (missing):
	    required by: world[calamares]

Signed-off-by: Gaël PORTAY <gael.portay@collabora.com>