host-apk-tools: add missing host-pkgconf dependency
This fixes the error below:

	/usr/bin/ld: src/apk.o: in function `main':
	apk.c:(.text.startup+0x3f0): undefined reference to `OPENSSL_init_crypto'
	/usr/bin/ld: apk.c:(.text.startup+0x3f5): undefined reference to `ENGINE_load_builtin_engines'
	/usr/bin/ld: apk.c:(.text.startup+0x3fa): undefined reference to `ENGINE_register_all_complete'
	/usr/bin/ld: src/add.o: in function `add_main':
	add.c:(.text+0x1f9): undefined reference to `EVP_MD_CTX_new'
	/usr/bin/ld: add.c:(.text+0x201): undefined reference to `EVP_sha1'
	/usr/bin/ld: add.c:(.text+0x20e): undefined reference to `EVP_DigestInit_ex'
	/usr/bin/ld: add.c:(.text+0x21e): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: add.c:(.text+0x230): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: add.c:(.text+0x254): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: add.c:(.text+0x25c): undefined reference to `EVP_MD_CTX_md'
	/usr/bin/ld: add.c:(.text+0x264): undefined reference to `EVP_MD_size'
	/usr/bin/ld: add.c:(.text+0x27e): undefined reference to `EVP_DigestFinal_ex'
	/usr/bin/ld: add.c:(.text+0x286): undefined reference to `EVP_MD_CTX_free'
	/usr/bin/ld: src/fetch.o: in function `cup':
	fetch.c:(.text+0x59e): undefined reference to `uncompress'
	/usr/bin/ld: src/database.o: in function `format_tmpname':
	database.c:(.text+0x90a): undefined reference to `EVP_MD_CTX_new'
	/usr/bin/ld: database.c:(.text+0x91b): undefined reference to `EVP_sha256'
	/usr/bin/ld: database.c:(.text+0x928): undefined reference to `EVP_DigestInit_ex'
	/usr/bin/ld: database.c:(.text+0x94c): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: database.c:(.text+0x964): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: database.c:(.text+0x978): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: database.c:(.text+0x98e): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: database.c:(.text+0x99b): undefined reference to `EVP_DigestFinal_ex'
	/usr/bin/ld: database.c:(.text+0x9a6): undefined reference to `EVP_MD_CTX_free'
	/usr/bin/ld: src/database.o: in function `apk_db_add_repository':
	database.c:(.text+0x52af): undefined reference to `EVP_sha1'
	/usr/bin/ld: database.c:(.text+0x52d0): undefined reference to `EVP_MD_size'
	/usr/bin/ld: database.c:(.text+0x52f6): undefined reference to `EVP_Digest'
	/usr/bin/ld: src/package.o: in function `apk_sign_ctx_parse_pkginfo_line':
	package.c:(.text+0x9b): undefined reference to `EVP_sha256'
	/usr/bin/ld: package.c:(.text+0xa7): undefined reference to `EVP_MD_size'
	/usr/bin/ld: src/package.o: in function `apk_sign_ctx_mpart_cb':
	package.c:(.text+0x125): undefined reference to `EVP_DigestInit_ex'
	/usr/bin/ld: package.c:(.text+0x133): undefined reference to `EVP_MD_CTX_set_flags'
	/usr/bin/ld: package.c:(.text+0x18d): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: package.c:(.text+0x1d0): undefined reference to `EVP_DigestFinal_ex'
	/usr/bin/ld: package.c:(.text+0x22e): undefined reference to `EVP_MD_CTX_clear_flags'
	/usr/bin/ld: package.c:(.text+0x23d): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: package.c:(.text+0x278): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: package.c:(.text+0x29c): undefined reference to `EVP_DigestFinal_ex'
	/usr/bin/ld: package.c:(.text+0x2a5): undefined reference to `EVP_MD_CTX_md'
	/usr/bin/ld: package.c:(.text+0x2ad): undefined reference to `EVP_MD_size'
	/usr/bin/ld: package.c:(.text+0x2be): undefined reference to `EVP_MD_CTX_md'
	/usr/bin/ld: package.c:(.text+0x2c6): undefined reference to `EVP_MD_size'
	/usr/bin/ld: package.c:(.text+0x356): undefined reference to `EVP_MD_CTX_md'
	/usr/bin/ld: package.c:(.text+0x35e): undefined reference to `EVP_MD_size'
	/usr/bin/ld: package.c:(.text+0x370): undefined reference to `EVP_DigestFinal_ex'
	/usr/bin/ld: package.c:(.text+0x3b2): undefined reference to `EVP_VerifyFinal'
	/usr/bin/ld: package.c:(.text+0x3dd): undefined reference to `EVP_MD_CTX_md'
	/usr/bin/ld: package.c:(.text+0x3e5): undefined reference to `EVP_MD_size'
	/usr/bin/ld: package.c:(.text+0x3f7): undefined reference to `EVP_DigestFinal_ex'
	/usr/bin/ld: src/package.o: in function `apk_sign_ctx_init':
	package.c:(.text+0x14ec): undefined reference to `EVP_md_null'
	/usr/bin/ld: package.c:(.text+0x14f5): undefined reference to `EVP_MD_CTX_new'
	/usr/bin/ld: package.c:(.text+0x1507): undefined reference to `EVP_DigestInit_ex'
	/usr/bin/ld: package.c:(.text+0x1529): undefined reference to `EVP_sha1'
	/usr/bin/ld: package.c:(.text+0x153c): undefined reference to `EVP_sha1'
	/usr/bin/ld: package.c:(.text+0x1561): undefined reference to `EVP_md_null'
	/usr/bin/ld: src/package.o: in function `apk_sign_ctx_free':
	package.c:(.text+0x1592): undefined reference to `EVP_PKEY_free'
	/usr/bin/ld: src/package.o: in function `apk_sign_ctx_process_file':
	package.c:(.text+0x172f): undefined reference to `OBJ_nid2sn'
	/usr/bin/ld: package.c:(.text+0x1737): undefined reference to `EVP_get_digestbyname'
	/usr/bin/ld: package.c:(.text+0x1781): undefined reference to `BIO_new_fp'
	/usr/bin/ld: package.c:(.text+0x1792): undefined reference to `PEM_read_bio_PUBKEY'
	/usr/bin/ld: package.c:(.text+0x17c4): undefined reference to `BIO_free'
	/usr/bin/ld: src/package.o: in function `apk_sign_ctx_init':
	package.c:(.text+0x151b): undefined reference to `EVP_MD_CTX_set_flags'
	/usr/bin/ld: src/package.o: in function `apk_sign_ctx_free':
	package.c:(.text+0x159c): undefined reference to `EVP_MD_CTX_free'
	/usr/bin/ld: src/archive.o: in function `tar_entry_read':
	archive.c:(.text+0x65): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: archive.c:(.text+0x9d): undefined reference to `EVP_MD_CTX_md'
	/usr/bin/ld: archive.c:(.text+0xa5): undefined reference to `EVP_MD_size'
	/usr/bin/ld: archive.c:(.text+0xb7): undefined reference to `EVP_DigestFinal_ex'
	/usr/bin/ld: src/archive.o: in function `apk_tar_parse':
	archive.c:(.text+0x129): undefined reference to `EVP_MD_CTX_new'
	/usr/bin/ld: archive.c:(.text+0x233): undefined reference to `EVP_MD_CTX_free'
	/usr/bin/ld: archive.c:(.text+0x5f5): undefined reference to `EVP_sha1'
	/usr/bin/ld: archive.c:(.text+0x607): undefined reference to `EVP_DigestInit_ex'
	/usr/bin/ld: archive.c:(.text+0xab2): undefined reference to `EVP_sha1'
	/usr/bin/ld: archive.c:(.text+0xae3): undefined reference to `EVP_Digest'
	/usr/bin/ld: src/io.o: in function `apk_fileinfo_hash_xattr_array':
	io.c:(.text+0x1081): undefined reference to `EVP_MD_CTX_new'
	/usr/bin/ld: io.c:(.text+0x10a9): undefined reference to `EVP_sha1'
	/usr/bin/ld: io.c:(.text+0x10b6): undefined reference to `EVP_DigestInit_ex'
	/usr/bin/ld: io.c:(.text+0x10f4): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: io.c:(.text+0x1101): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: io.c:(.text+0x1121): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: io.c:(.text+0x112e): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: io.c:(.text+0x1147): undefined reference to `EVP_MD_CTX_md'
	/usr/bin/ld: io.c:(.text+0x114f): undefined reference to `EVP_MD_size'
	/usr/bin/ld: io.c:(.text+0x1164): undefined reference to `EVP_DigestFinal_ex'
	/usr/bin/ld: src/io.o: in function `apk_fileinfo_hash_xattr':
	io.c:(.text+0x11a5): undefined reference to `EVP_sha1'
	/usr/bin/ld: src/io.o: in function `apk_fileinfo_get':
	io.c:(.text+0x12d1): undefined reference to `EVP_MD_CTX_new'
	/usr/bin/ld: io.c:(.text+0x12fa): undefined reference to `EVP_sha1'
	/usr/bin/ld: io.c:(.text+0x1307): undefined reference to `EVP_DigestInit_ex'
	/usr/bin/ld: io.c:(.text+0x1327): undefined reference to `EVP_DigestUpdate'
	/usr/bin/ld: io.c:(.text+0x1345): undefined reference to `EVP_MD_CTX_md'
	/usr/bin/ld: io.c:(.text+0x134d): undefined reference to `EVP_MD_size'
	/usr/bin/ld: io.c:(.text+0x135e): undefined reference to `EVP_DigestFinal_ex'
	/usr/bin/ld: io.c:(.text+0x1366): undefined reference to `EVP_MD_CTX_free'
	/usr/bin/ld: io.c:(.text+0x14a0): undefined reference to `EVP_md_null'
	/usr/bin/ld: io.c:(.text+0x14c2): undefined reference to `EVP_Digest'
	/usr/bin/ld: io.c:(.text+0x14d1): undefined reference to `EVP_md_null'
	/usr/bin/ld: io.c:(.text+0x14e1): undefined reference to `EVP_md5'
	/usr/bin/ld: io.c:(.text+0x15e5): undefined reference to `EVP_md_null'
	/usr/bin/ld: io.c:(.text+0x1739): undefined reference to `EVP_MD_CTX_set_flags'
	/usr/bin/ld: io.c:(.text+0x175e): undefined reference to `EVP_sha1'
	/usr/bin/ld: io.c:(.text+0x1796): undefined reference to `EVP_md5'
	/usr/bin/ld: io.c:(.text+0x17c8): undefined reference to `EVP_sha1'
	/usr/bin/ld: io.c:(.text+0x17e3): undefined reference to `EVP_md5'
	/usr/bin/ld: src/io.o: in function `apk_fileinfo_hash_xattr_array':
	io.c:(.text+0x118a): undefined reference to `EVP_MD_CTX_free'
	/usr/bin/ld: src/gunzip.o: in function `gzi_close':
	gunzip.c:(.text+0x19): undefined reference to `inflateEnd'
	/usr/bin/ld: src/gunzip.o: in function `gzo_write':
	gunzip.c:(.text+0x8a): undefined reference to `deflate'
	/usr/bin/ld: src/gunzip.o: in function `gzo_close':
	gunzip.c:(.text+0x152): undefined reference to `deflate'
	/usr/bin/ld: gunzip.c:(.text+0x191): undefined reference to `deflateEnd'
	/usr/bin/ld: src/gunzip.o: in function `gzi_read':
	gunzip.c:(.text+0x313): undefined reference to `inflate'
	/usr/bin/ld: gunzip.c:(.text+0x405): undefined reference to `inflateEnd'
	/usr/bin/ld: gunzip.c:(.text+0x41a): undefined reference to `inflateInit2_'
	/usr/bin/ld: src/gunzip.o: in function `apk_bstream_gunzip_mpart':
	gunzip.c:(.text+0x533): undefined reference to `inflateInit2_'
	/usr/bin/ld: src/gunzip.o: in function `apk_ostream_gzip':
	gunzip.c:(.text+0x5dd): undefined reference to `deflateInit2_'
	/usr/bin/ld: libfetch/libfetch.a(common.o): in function `fetch_ssl':
	common.c:(.text+0x8cc): undefined reference to `OPENSSL_init_ssl'
	/usr/bin/ld: common.c:(.text+0x8e7): undefined reference to `OPENSSL_init_ssl'
	/usr/bin/ld: common.c:(.text+0x8ec): undefined reference to `TLS_client_method'
	/usr/bin/ld: common.c:(.text+0x8f8): undefined reference to `SSL_CTX_new'
	/usr/bin/ld: common.c:(.text+0x910): undefined reference to `SSL_CTX_ctrl'
	/usr/bin/ld: common.c:(.text+0x931): undefined reference to `SSL_CTX_set_default_verify_paths'
	/usr/bin/ld: common.c:(.text+0x940): undefined reference to `SSL_CTX_set_verify'
	/usr/bin/ld: common.c:(.text+0x988): undefined reference to `SSL_CTX_use_certificate_chain_file'
	/usr/bin/ld: common.c:(.text+0x9ab): undefined reference to `SSL_CTX_use_PrivateKey_file'
	/usr/bin/ld: common.c:(.text+0x9c7): undefined reference to `SSL_new'
	/usr/bin/ld: common.c:(.text+0x9ec): undefined reference to `SSL_set_fd'
	/usr/bin/ld: common.c:(.text+0x9ff): undefined reference to `SSL_ctrl'
	/usr/bin/ld: common.c:(.text+0xa11): undefined reference to `SSL_connect'
	/usr/bin/ld: common.c:(.text+0xa23): undefined reference to `SSL_get_peer_certificate'
	/usr/bin/ld: common.c:(.text+0xa88): undefined reference to `SSL_CTX_get_cert_store'
	/usr/bin/ld: common.c:(.text+0xa92): undefined reference to `X509_LOOKUP_file'
	/usr/bin/ld: common.c:(.text+0xa9f): undefined reference to `X509_STORE_add_lookup'
	/usr/bin/ld: common.c:(.text+0xab4): undefined reference to `X509_load_crl_file'
	/usr/bin/ld: common.c:(.text+0xb20): undefined reference to `X509_check_host'
	/usr/bin/ld: common.c:(.text+0xb32): undefined reference to `SSL_get_current_cipher'
	/usr/bin/ld: common.c:(.text+0xb3a): undefined reference to `SSL_CIPHER_get_name'
	/usr/bin/ld: common.c:(.text+0xb54): undefined reference to `X509_get_subject_name'
	/usr/bin/ld: common.c:(.text+0xb60): undefined reference to `X509_NAME_oneline'
	/usr/bin/ld: common.c:(.text+0xb85): undefined reference to `X509_get_issuer_name'
	/usr/bin/ld: common.c:(.text+0xb91): undefined reference to `X509_NAME_oneline'
	/usr/bin/ld: common.c:(.text+0xc4b): undefined reference to `X509_STORE_set_flags'
	/usr/bin/ld: common.c:(.text+0xc58): undefined reference to `SSL_CTX_load_verify_locations'
	/usr/bin/ld: common.c:(.text+0xc83): undefined reference to `X509_check_host'
	/usr/bin/ld: common.c:(.text+0xcf8): undefined reference to `ERR_print_errors_fp'
	/usr/bin/ld: libfetch/libfetch.a(common.o): in function `fetch_read':
	common.c:(.text+0xdcf): undefined reference to `SSL_read'
	/usr/bin/ld: common.c:(.text+0xf22): undefined reference to `SSL_get_error'
	/usr/bin/ld: libfetch/libfetch.a(common.o): in function `fetch_write':
	common.c:(.text+0x12e9): undefined reference to `SSL_write'
	/usr/bin/ld: libfetch/libfetch.a(common.o): in function `fetch_close':
	common.c:(.text+0x1364): undefined reference to `SSL_shutdown'
	/usr/bin/ld: common.c:(.text+0x136d): undefined reference to `SSL_set_connect_state'
	/usr/bin/ld: common.c:(.text+0x1376): undefined reference to `SSL_free'
	/usr/bin/ld: common.c:(.text+0x1384): undefined reference to `SSL_CTX_free'
	/usr/bin/ld: common.c:(.text+0x1392): undefined reference to `X509_free'
	collect2: error: ld returned 1 exit status